# Create a GitHub action to email a report from a file at 6 a.m. daily.

name: Email Report
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Email Report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Report"
          body: "Hello, this is your daily report."
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/plain
          attachments: |
            deploy-app.yml
```

### 4. Create a GitHub action to run a job at a specific time

```yaml
# Path: deploy-app.yml
# Create a GitHub action to run a job at a specific time.

name: Deploy App
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: actions/checkout@v2
      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu
            git clone